//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chest.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chesters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chesters()
        {
            this.Zakazs = new HashSet<Zakazs>();
        }
    
        public int ID_Chester { get; set; }
        public int ID_Category { get; set; }
        public int ID_Firm { get; set; }
        public string Количество { get; set; }
        public Nullable<System.DateTime> Дата_поступления { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Название { get; set; }
    
        public virtual Categorys Categorys { get; set; }
        public virtual Firms Firms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazs> Zakazs { get; set; }
    }
}
