//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chest.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID_Client { get; set; }
        public int ID_Zakaz { get; set; }
        public string Адрес { get; set; }
        public string ИНН { get; set; }
        public string Номер_телефона { get; set; }
        public string ФИО { get; set; }
    
        public virtual Zakazs Zakazs { get; set; }
    }
}
