//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chest.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firms()
        {
            this.Chesters = new HashSet<Chesters>();
        }
    
        public int ID_Firm { get; set; }
        public Nullable<int> ID_Chester { get; set; }
        public string Наименование { get; set; }
        public string Юр_Лицо { get; set; }
        public string Физ_Лицо { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chesters> Chesters { get; set; }
    }
}
