//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chest.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChestEntities : DbContext
    {
        public ChestEntities()
            : base("name=ChestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorys> Categorys { get; set; }
        public virtual DbSet<Chesters> Chesters { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zakazs> Zakazs { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
    }
}
