//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chest.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int id_pic { get; set; }
        public string pic { get; set; }
        public string info { get; set; }
    }
}
