//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chest.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_Users { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    }
}
